{% set name = "moviepy" %}
{% set version = "2.0.0.dev2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: c0567bbaaf17936f498b53f40b8c1e2d7667d4b917f775cac610c4af382d174f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - decorator >=4.0.2,<5.0
    - imageio >=2.5,<3.0
    - imageio_ffmpeg >=0.2.0
    - numpy >=1.17.3
    - pip
    - proglog <=1.0.0
    - python
    - requests >=2.8.1,<3.0
  run:
    - decorator >=4.0.2,<5.0
    - imageio >=2.5,<3.0
    - imageio_ffmpeg >=0.2.0
    - numpy >=1.17.3
    - proglog <=1.0.0
    - python
    - requests >=2.8.1,<3.0

test:
  imports:
    - moviepy
    - moviepy.audio
    - moviepy.audio.fx
    - moviepy.audio.fx.all
    - moviepy.audio.io
    - moviepy.audio.tools
    - moviepy.video
    - moviepy.video.compositing
    - moviepy.video.fx
    - moviepy.video.fx.all
    - moviepy.video.io
    - moviepy.video.tools
  requires:
    - coverage <5.0
    - coveralls >=1.1,<2.0
    - pytest >=3.0.0,<4.0
    - pytest-cov >=2.5.1,<3.0
    - requests >=2.8.1,<3.0

about:
  home: "https://zulko.github.io/moviepy/"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Video editing with Python"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
